### ISSUE TITLE
Stow

### ISSUE THREAD

**Issue by sciunto** [hmaarrfk/linux-tools#1]
Try https://www.gnu.org/software/stow/ instead of ln -s :)

**Comment by hmaarrfk** [comment]
Man how did you find this stuff. 

I wish these dot files actually worked.

I feel like there is enough variation between upgrades that it gets out of hand. 

Not to mention that the base bashrc isn’t blank. So I always have to watch out not to overwrite ubuntu’s configuration. 

rvm for ruby also likes to just add things that are version pinned in there. 

Anyway. Thanks for tips. I’ll try stow

**Comment by hmaarrfk** [comment]
ok, i use stow now :D

**Comment by hmaarrfk** [comment]
as anticipated, the storage method has changed, and I now use `chezmoi`. A little more direct. and easier to install. maybe.

**Comment by sciunto** [comment]
thanks for sharing!

**Comment by hmaarrfk** [comment]
I also ended up using a private github repo.

Kinda sucks since I can't share things anymore, but ultimately, there ended up being sensitive info in my config file.

**Comment by sciunto** [comment]
I also host a private repo with gitea on a personal server for this purpose. ;)

**Comment by hmaarrfk** [comment]
yeah... nothing is ideal for private files.
